api:
  dashboard: true
  insecure: true # Nur für Homelab, entferne in Produktion

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///run/podman/podman.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: sgesang@mailo.com # Ersetze mit deiner E-Mail
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
